#!/bin/bash
# Generates the compressed decode-only fixtures the on-device corpus needs.
# PCM containers (wav/aiff/caf/w64) and the codecs the engine can encode
# (aac/alac/flac) are produced on device by the engine itself, so only formats
# the build cannot write are baked in here.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/example/src/fixtures"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

DURATION=1
RATE=44100
TONE="sine=frequency=440:sample_rate=$RATE:duration=$DURATION"

ffmpeg -v error -f lavfi -i "$TONE" -ac 1 -c:a libmp3lame -b:a 64k "$TMP/tone.mp3"
# The native Vorbis encoder only writes stereo, which doubles as the corpus'
# stereo decode + downmix fixture.
ffmpeg -v error -f lavfi -i "$TONE" -ac 2 -strict -2 -c:a vorbis -b:a 64k "$TMP/tone.ogg"
ffmpeg -v error -f lavfi -i "$TONE" -ac 1 -c:a libopus -b:a 64k "$TMP/tone.opus.ogg"
ffmpeg -v error -f lavfi -i "$TONE" -ac 1 -c:a libopus -b:a 64k -f webm "$TMP/tone.webm"

{
  echo "// Generated by scripts/generate-fixtures.sh — do not edit by hand."
  echo "// Formats this build can decode but not encode, so the on-device corpus"
  echo "// cannot produce them itself. Each is a 1s 440 Hz mono tone at 44100 Hz."
  echo
  for entry in "MP3_BASE64:tone.mp3" "OGG_VORBIS_BASE64:tone.ogg" "OGG_OPUS_BASE64:tone.opus.ogg" "WEBM_OPUS_BASE64:tone.webm"; do
    NAME=${entry%%:*}
    FILE=${entry#*:}
    echo "export const $NAME ="
    echo "  '$(base64 < "$TMP/$FILE" | tr -d '\n')'"
    echo
  done
} > "$OUT/media.ts"

echo "==> wrote $OUT/media.ts ($(wc -c < "$OUT/media.ts") bytes)"
